Repository zero-to-mastery/ZTM-Quest, pull requests merged in 2024-10, with the labels that each got.

#40 add dummy mailbox interaction
  src/interactions/map_start/index.js
  src/interactions/map_start/mailboxMainArea.interaction.js
Labels: hacktoberfest-accepted

#45 Add a computer sprite to map_start in room 1 (issue #35)
  public/laptop.png
  src/gameObjects/map_start/computer.gameObject.js
  src/gameObjects/map_start/index.js
  src/interactions/map_start/computer.interaction.js
  src/interactions/map_start/index.js
Labels: hacktoberfest-accepted

#43 issue no.20 solved dialogue box UI updated
  index.html
  src/interactions/map_start/bruno.interaction.js
  src/interactions/map_start/enterMapCity.interaction.js
  src/interactions/map_start/mailboxMainArea.interaction.js
  src/interactions/map_start/restroom.interactions.js
  src/utils.js
Labels: hacktoberfest-accepted

#50 FEAT: Adds capability to save game state and load it
  src/factories/player.factory.js
  src/interactions/map_start/bruno.interaction.js
  src/interactions/map_start/enterMapCity.interaction.js
  src/interactions/map_start/restroom.interactions.js
  src/scenes/start.js
  src/utils/gameState.js
Labels: hacktoberfest-accepted

#56 My feature branch
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/interactions/map_start/index.js
  src/interactions/map_start/jokeTeller.interaction.js
Labels: hacktoberfest-accepted

#57 Fetch only safe-mode jokes
  src/interactions/map_start/jokeTeller.interaction.js
Labels: good first issue, hacktoberfest

#63 Add interaction for computer in room 1 + fix formatting in other files to pass CI checks
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/interactions/map_start/computer.interaction.js
  src/interactions/map_start/jokeTeller.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#68 FIX: existing interactions
  .github/workflows/code-quality-checks.yaml
  .github/workflows/code-style-fix.yaml
  src/interactions/map_start/bruno.interaction.js
  src/interactions/map_start/jokeTeller.interaction.js
  src/interactions/map_start/restroom.interactions.js
Labels: hacktoberfest-accepted

#53 Adding misterFu game object
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/misterFu.gameObject.js
Labels: hacktoberfest, hacktoberfest-accepted

#58 Changed The Position
  package-lock.json
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/interactions/map_start/jokeTeller.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#64 New Interaction Drink Machine
  index.html
  src/interactions/map_start/drink_machine.interaction.js
  src/interactions/map_start/index.js
Labels: hacktoberfest, hacktoberfest-accepted

#70 FIX: mister fu sprite slice
  .github/workflows/code-style-fix.yaml
  src/gameObjects/map_start/misterFu.gameObject.js
Labels: hacktoberfest, hacktoberfest-accepted

#71 Fix Dialog Overwriting Issue by Managing User Interaction with computer
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/interactions/map_start/computer.interaction.js
  src/interactions/map_start/jokeTeller.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#62 fix:canvas focus after dialogs fixed
  src/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added all Interactions from one map to other along with a permission …
  src/interactions/map_arcade/enterMapCity.interactions.js
  src/interactions/map_city/enterMapArcade.interactions.js
  src/interactions/map_city/enterMapStart.interaction.js
  src/interactions/map_city/index.js
  src/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#72 Return focus to canvas after interactions with dialogs
  index.html
  src/interactions/map_start/drink_machine.interaction.js
  src/main.js
  src/styles/dialogs.css
  src/styles/global.css
  src/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#74 Abstract events and more
  index.html
  src/kplayCtx.js
  src/player.controls.js
  src/styles/global.css
  src/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#77 multiple city interactions are added
  src/interactions/map_city/boundaryArcade.interaction.js
  src/interactions/map_city/boundaryBurgerBar.interaction.js
  src/interactions/map_city/index.js
  src/interactions/map_city/snackBars.interactions.js
  src/interactions/map_city/stalls.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#69 MisterFu interactions
  src/constants.js
  src/gameObjects/map_start/misterFu.gameObject.js
  src/interactions/map_start/index.js
  src/interactions/map_start/misterFu.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#79 Adds keyboard navitagion (tab, enter/space)
  src/interactions/map_start/drink_machine.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#81 Fix dialogue import and call
  src/interactions/map_start/misterFu.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#84 FIX: genereal refractoring, also closes #83
  .github/workflows/code-quality-checks.yaml
  .github/workflows/code-style-fix.yaml
  eslint.config.js
  package-lock.json
  package.json
  src/gameObjects/map_start/bruno.gameObject.js
  src/gameObjects/map_start/cake.gameObject.js
  src/gameObjects/map_start/computer.gameObject.js
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/gameObjects/map_start/misterFu.gameObject.js
  src/interactions/map_start/jokeTeller.interaction.js
  src/interactions/map_start/misterFu.interaction.js
  src/utils.js
Labels: hacktoberfest, hacktoberfest-accepted

#82 added turning on/off tv in main room
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/tv_main_room_video.gameObject.js
  src/interactions/map_start/index.js
  src/interactions/map_start/tv_main_room.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#86 FEAT: add auto labeling for hacktoberfest
  .github/workflows/code-quality-checks.yaml
Labels: hacktoberfest-accepted

#89 Added more NPCs in sinks, restrooms, and counch table in map_start
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/randNpcsOnRestroomSinkCounch.gameObject.js
Labels: hacktoberfest-accepted

#90 add hacktoberfest labeling
  .github/workflows/hacktoberfest-label.yaml
Labels: hacktoberfest-accepted

#87 added cake interaction
  src/interactions/map_start/cake.interaction.js
  src/interactions/map_start/index.js
Labels: hacktoberfest-accepted

#88 Created new forest map
  asset_credits.md
  public/exports/maps/map_forest.png
  public/forest_sprites.png
  public/maps/map_forest.json
  public/maps/map_start.json
  src/gameObjects/map_forest/butterfly.gameObject.js
  src/gameObjects/map_forest/index.js
  src/interactions/map_city/enterMapForest.interactions.js
  src/interactions/map_city/index.js
  src/interactions/map_forest/index.js
  src/scenes/forest.js
Labels: hacktoberfest-accepted

#94 Added NPCs
  src/gameObjects/map_city/index.js
  src/gameObjects/map_city/npcsOnmap_city.js
Labels: hacktoberfest-accepted

#98 fix: Interacting with game_machine_2
  package-lock.json
  src/interactions/map_arcade/game_machine_2.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#100 Arcade game
  asset_credits.md
  public/doux.png
  src/interactions/map_arcade/game_machine_6.interactions.js
  src/interactions/map_arcade/index.js
  src/interactions/map_campus_house_1/enterMapCity.interactions.js
Labels: hacktoberfest-accepted

#99 Changed the action modal to have nicer UI
  index.html
  public/TKey.png
  public/maps/map_forest_junction.json
  public/question-bubble.png
  src/init/map.init.js
  src/interactions/handler.interactions.js
  src/interactions/map_forest_junction/flowers.interactions.js
  src/interactions/map_forest_junction/index.js
  src/interactions/map_forest_junction/tree.interactions.js
  src/interactions/map_start/bruno.interaction.js
  src/interactions/map_start/jokeTeller.interaction.js
  src/interactions/map_start/misterFu.interaction.js
  src/utils.js
Labels: hacktoberfest-accepted

#107 Bug in UI found; Made assets folder & restructured public
  HOWTO_Add-Game-Objects.md
  index.html
  public/assets/fonts/PixelifySans-VariableFont_wght.ttf
  public/assets/fonts/monogram.ttf
  public/assets/sprites/TKey.png
  public/assets/sprites/bruno.png
  public/assets/sprites/cake.png
  public/assets/sprites/campus_house_door_1.png
  public/assets/sprites/characters.png
  public/assets/sprites/doux.png
  public/assets/sprites/favicon-32x32.png
  public/assets/sprites/forest_sprites.png
  public/assets/sprites/game_cover.png
  public/assets/sprites/laptop.png
  public/assets/sprites/question-bubble.png
  public/assets/sprites/ztm_logo.png
  public/assets/sprites/ztm_logo_64x64.png
  public/assets/sprites/ztm_trailer.png
  src/constants.js
  src/factories/npc.factory.js
  src/factories/player.factory.js
  src/gameObjects/map_city/campusHouse1OpenDoor.js
  src/gameObjects/map_forest/butterfly.gameObject.js
  src/gameObjects/map_start/bruno.gameObject.js
  src/gameObjects/map_start/cake.gameObject.js
  src/gameObjects/map_start/computer.gameObject.js
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/gameObjects/map_start/misterFu.gameObject.js
  src/gameObjects/map_start/tv_main_room_video.gameObject.js
  src/gameObjects/map_start/ztmTrailer.gameObject.js
  src/interactions/map_arcade/game_machine_6.interactions.js
  src/utils.js
Labels: hacktoberfest-accepted

#105 fix: focus canvas after dialog end
  src/utils.js
Labels: hacktoberfest-accepted

#110 Added new arcade game for game_machine_4, including sound effect
  asset_credits.md
  public/assets/sprites/bird.png
  public/assets/sprites/game_over.wav
  public/assets/sprites/jump.wav
  public/assets/sprites/pipe.png
  src/interactions/map_arcade/game_machine_4.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#109 game machine 6 improvements
  src/interactions/map_arcade/game_machine_6.interactions.js
Labels: hacktoberfest-accepted

#111 game machine 6 improvements
  asset_credits.md
  public/assets/sprites/cloud1.png
  public/assets/sprites/cloud2.png
  public/assets/sprites/cloud3.png
  public/assets/sprites/dino_floor.png
  public/assets/sprites/tree001.png
  public/assets/sprites/tree002.png
  public/assets/sprites/tree003.png
  public/assets/sprites/tree004.png
  src/interactions/map_arcade/game_machine_6.interactions.js
Labels: hacktoberfest-accepted

#112 Added Machine Game and NPCs in Arcade MAP
  src/gameObjects/map_arcade/index.js
  src/gameObjects/map_arcade/npcsOnmap.js
  src/interactions/map_arcade/game_machine_8.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#116 Added controls for smartphone and resized some texts for responsiveness
  src/interactions/map_arcade/game_machine_4.interactions.js
Labels: hacktoberfest-accepted

#117 fix: correct image links in README.md
  Readme.md
Labels: hacktoberfest-accepted

#85 Jessie arcade
  src/constants.js
  src/gameObjects/map_arcade/index.js
  src/gameObjects/map_arcade/jessie.gameObject.js
  src/interactions/map_arcade/index.js
  src/interactions/map_arcade/jessie.interaction.js
  src/interactions/map_start/misterFu.interaction.js
Labels: hacktoberfest, hacktoberfest-accepted

#118 add mini game in the arcade room for game machine 10
  public/assets/sprites/moon.png
  src/interactions/map_arcade/game_machine_10.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#113 Gba frame
  index.html
  src/init/map.init.js
  src/interactions/handler.interactions.js
  src/player.controls.js
  src/styles/dialogs.css
  src/styles/global.css
  src/styles/screen.css
  src/utils.js
Labels: hacktoberfest-accepted

#125 feat: add energy mechanic
  index.html
  src/constants.js
  src/interactions/map_city/boundaryBurgerBar.interaction.js
  src/interactions/map_city/snackBars.interactions.js
  src/interactions/map_city/stalls.interaction.js
  src/interactions/map_start/drink_machine.interaction.js
  src/main.js
  src/utils.js
  src/utils/energyUpdate.js
  src/utils/gameState.js
Labels: hacktoberfest-accepted

#128 feat: add sleep beed interaction
  src/interactions/map_campus_house_1/bed.interaction.js
  src/interactions/map_campus_house_1/index.js
Labels: hacktoberfest-accepted

#129 Created a mini game like the offline dino game in the arcade room for game machine 11
  asset_credits.md
  public/assets/sounds/celebratingformulas.mp3
  public/assets/sounds/celebratingtrophies.mp3
  public/assets/sounds/formulacrash.mp3
  public/assets/sounds/formulaovertake.mp3
  public/assets/sounds/lightstart.mp3
  public/assets/sounds/racemusic.mp3
  public/assets/sounds/racemusic2.mp3
  public/assets/sounds/racestart.mp3
  public/assets/sounds/spectators.mp3
  public/assets/sounds/trophycollected.mp3
  public/assets/sounds/trophylost.mp3
  public/assets/sprites/RaceBackground.png
  public/assets/sprites/formula.png
  public/assets/sprites/formulasheet.png
  public/assets/sprites/newformulasheet.png
  public/assets/sprites/trophy.png
  src/interactions/map_arcade/game_machine_11.interaction.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#131 FIX: Restructoring for performance
  public/exports/maps/map_city.png
  public/maps/map_arcade.json
  public/maps/map_campus_house_1.json
  public/maps/map_city.json
  src/core/kaplay/gameObjects/index.js
  src/core/kaplay/interactions/index.js
  src/factories/npc.factory.js
  src/factories/player.factory.js
  src/gameObjects/map_arcade/index.js
  src/gameObjects/map_arcade/jessie.gameObject.js
  src/gameObjects/map_arcade/npcsOnmap.js
  src/gameObjects/map_campus_house_1/index.js
  src/gameObjects/map_city/campusHouse1OpenDoor.js
  src/gameObjects/map_city/index.js
  src/gameObjects/map_city/npcsOnmap_city.js
  src/gameObjects/map_forest/index.js
  src/gameObjects/map_forest_junction/index.js
  src/gameObjects/map_start/bruno.gameObject.js
  src/gameObjects/map_start/cake.gameObject.js
  src/gameObjects/map_start/computer.gameObject.js
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/jokeTellerNPC.gameObject.js
  src/gameObjects/map_start/misterFu.gameObject.js
  src/gameObjects/map_start/npcsOnChairs.gameObject.js
  src/gameObjects/map_start/randNpcsOnRestroomSinkCounch.gameObject.js
  src/gameObjects/map_start/tv_main_room_video.gameObject.js
  src/gameObjects/map_start/ztmTrailer.gameObject.js
  src/init/map.init.js
  src/interactions/map_arcade/enterMapCity.interactions.js
  src/interactions/map_arcade/index.js
  src/interactions/map_campus_house_1/enterMapCity.interactions.js
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_city/enterMapArcade.interactions.js
  src/interactions/map_city/enterMapCampusHouse1.interaction.js
  src/interactions/map_city/enterMapForestJunction.interactions.js
  src/interactions/map_city/enterMapStartLeft.interactions.js
  src/interactions/map_city/enterMapStartRight.interactions.js
  src/interactions/map_city/index.js
  src/interactions/map_forest/enterMapForestJunction.interactions.js
  src/interactions/map_forest/index.js
  src/interactions/map_forest_junction/enterMapCity.interactions.js
  src/interactions/map_forest_junction/enterMapForest.interactions.js
  src/interactions/map_forest_junction/index.js
  src/interactions/map_start/cake.interaction.js
  src/interactions/map_start/computer.interaction.js
  src/interactions/map_start/enterMapCityLeft.interaction.js
  src/interactions/map_start/enterMapCityRight.interactions.js
  src/interactions/map_start/index.js
  src/interactions/map_start/tv_main_room.interaction.js
  src/kplayCtx.js
  src/main.js
  src/player.controls.js
  src/scenes/arcade.js
  src/scenes/bootstrap.js
  src/scenes/campus_house_1.js
  src/scenes/city.js
  src/scenes/forest.js
  src/scenes/forest_junction.js
  src/scenes/start.js
  src/utils.js
Labels: hacktoberfest-accepted

#132 Feature/add computer house 1
  src/gameObjects/map_campus_house_1/computer.gameObject.js
  src/gameObjects/map_campus_house_1/index.js
  src/interactions/map_campus_house_1/computer.interaction.js
  src/interactions/map_campus_house_1/index.js
  src/utils/energyUpdate.js
Labels: hacktoberfest-accepted

#103 game_machine_1 added
  src/interactions/map_arcade/game_machine_1.intercation.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#133 19 game machine 12
  src/interactions/map_arcade/game_machine_12.interaction.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#134 fix: change object location and iteraction
  src/gameObjects/map_campus_house_1/computer.gameObject.js
  src/interactions/map_campus_house_1/computer.interaction.js
Labels: hacktoberfest-accepted

#135 Add interaction for bedroom_vanity in map_campus_house_1
  src/interactions/map_campus_house_1/bedroomVanity.interaction.js
  src/interactions/map_campus_house_1/index.js
Labels: hacktoberfest-accepted

#140 Add kitchen_fridge and mage interaction to map_campus_house_1
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_campus_house_1/kitchenFridge.interaction.js
  src/interactions/map_campus_house_1/mage.interaction.js
Labels: hacktoberfest-accepted

#141 fixed scaling of floor/clouds/trees and added pause menu
  public/assets/sprites/dino_floor.png
  src/interactions/map_arcade/game_machine_6.interactions.js
Labels: hacktoberfest-accepted

#143 fix: adjust canvas size to accommodate debug log
  index.html
  src/player.controls.js
  src/styles/screen.css
  src/utils.js
Labels: hacktoberfest-accepted

#144 Add reusable getRandomTip function, create bedroom_shelf interaction
  src/interactions/map_campus_house_1/bedroomShelf.interaction.js
  src/interactions/map_campus_house_1/index.js
  src/utils/randomTip.js
Labels: hacktoberfest-accepted

#146 Added interactions in map_campus_house_1
  src/interactions/map_campus_house_1/bedroom_table.interaction.js
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_campus_house_1/livingRoomCouch.interaction.js
  src/utils/randomCodingJokes.js
  src/utils/randomJSQuestion.js
Labels: hacktoberfest-accepted

#147 added minimap for player
  index.html
  src/init/map.init.js
  src/kplayCtx.js
  src/player.controls.js
  src/utils.js
  src/utils/miniMap.js
Labels: hacktoberfest-accepted

#145 Game/flappy bird
  public/assets/sprites/1.png
  public/assets/sprites/2.png
  public/assets/sprites/3.png
  public/assets/sprites/background-day.png
  public/assets/sprites/bluebird-downflap.png
  public/assets/sprites/bluebird-midflap.png
  public/assets/sprites/bluebird-upflap.png
  public/assets/sprites/pipe-green.png
  src/interactions/map_arcade/game_machine_3.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#148 added a very basic crane game
  src/interactions/map_arcade/game_machine_crawl.interaction.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#151 Arcade game crane machine mobile update
  src/interactions/map_arcade/game_machine_crawl.interaction.js
Labels: hacktoberfest-accepted

#149 added a chest_treasure to the game objects: map_start
  public/assets/sounds/chest_opening.wav
  public/assets/sprites/treasure_chest_closed.png
  public/assets/sprites/treasure_chest_open.png
  src/gameObjects/map_start/index.js
  src/gameObjects/map_start/treasureChest.gameObject.js
Labels: hacktoberfest-accepted

#150 feat: add settings menu
  index.html
  src/styles/screen.css
  src/utils/settings.js
Labels: hacktoberfest-accepted

#152 Add moving cars animation on city map
  asset_credits.md
  public/assets/sprites/moving_cars.png
  src/gameObjects/map_city/index.js
  src/gameObjects/map_city/movingCars.js
Labels: hacktoberfest-accepted

#153 added sprint/running to player
  src/player.controls.js
Labels: hacktoberfest-accepted

#154 added map title and player icon to minimap
  index.html
  src/init/map.init.js
  src/player.controls.js
  src/styles/screen.css
  src/utils/miniMap.js
Labels: hacktoberfest-accepted

#161 added gM9
  src/interactions/map_arcade/game_machine_9.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#157 inventory creation for the game
  index.html
  src/inventory.js
  src/kplayCtx.js
  src/main.js
Labels: hacktoberfest-accepted

#160 Modified-Menu
  index.html
  public/assets/sounds/city.mp3
  public/assets/sprites/audio-on.png
  public/assets/sprites/debug.png
  public/assets/sprites/main_menu.png
  public/assets/sprites/mute.png
  public/assets/sprites/newgame.png
  public/assets/sprites/stats.png
  src/styles/screen.css
  src/utils/settings.js
Labels: hacktoberfest-accepted

#115 Issue-21 : Add gameOver scene functionality
  index.html
  public/exports/maps/academic_building.png
  src/main.js
  src/scenes/arcade.js
  src/scenes/city.js
  src/scenes/gameOver.js
  src/scenes/start.js
  src/utils.js
Labels: hacktoberfest-accepted

#164 Adding cat sprite to the start map
  asset_credits.md
  public/assets/sprites/cat.png
  src/gameObjects/map_start/cat.gameObject.js
  src/gameObjects/map_start/index.js
Labels: hacktoberfest-accepted

#166 fix: missing state props on load, move credits button
  index.html
  src/main.js
  src/utils/gameState.js
Labels: hacktoberfest-accepted

#170 Added a cat interaction
  src/interactions/map_start/cat.interaction.js
  src/interactions/map_start/index.js
Labels: hacktoberfest-accepted

#168 added current map into local storage
  src/core/kaplay/interactions/index.js
  src/main.js
  src/player.controls.js
  src/scenes/bootstrap.js
  src/utils/gameState.js
  src/utils/saveCurrentScene.js
Labels: hacktoberfest-accepted

#162 feat: add coins mechanic
  index.html
  src/gameObjects/map_start/treasureChest.gameObject.js
  src/interactions/map_arcade/game_machine_1.interactions.js
  src/interactions/map_arcade/game_machine_3.interactions.js
  src/interactions/map_arcade/game_machine_6.interactions.js
  src/interactions/map_arcade/game_machine_crawl.interaction.js
  src/interactions/map_city/boundaryBurgerBar.interaction.js
  src/interactions/map_city/snackBars.interactions.js
  src/interactions/map_city/stalls.interaction.js
  src/interactions/map_start/drink_machine.interaction.js
  src/main.js
  src/player.controls.js
  src/styles/screen.css
  src/utils.js
  src/utils/coinsUpdate.js
  src/utils/gameState.js
  src/utils/settings.js
Labels: hacktoberfest-accepted

#176 Bug fix for bootstrap
  src/scenes/bootstrap.js
  src/utils/resetPausingVariables.js
Labels: hacktoberfest-accepted

#174 added sounds to public
  public/assets/sounds/jungle-vibes.mp3
Labels: hacktoberfest-accepted

#179 feature: added bedroom_plant interaction
  src/interactions/map_campus_house_1/bedroom_plant.interaction.js
  src/interactions/map_campus_house_1/index.js
Labels: hacktoberfest-accepted

#178 Added Living room Interaction
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_campus_house_1/living_room_couch.interaction.js
Labels: hacktoberfest-accepted

#183 fix: change player state to proxy object
  src/constants.js
  src/interactions/map_arcade/jessie.interaction.js
  src/interactions/map_start/enterMapCityLeft.interaction.js
  src/interactions/map_start/enterMapCityRight.interactions.js
  src/scenes/gameMachine/lose.js
  src/utils/resetPausingVariables.js
Labels: hacktoberfest-accepted

#182 Word guessing mini game for game_machine_2
  src/interactions/map_arcade/game_machine_2.interactions.js
Labels: hacktoberfest-accepted

#187 add restroom_toilet interaction
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_campus_house_1/restroom_toilet.interaction.js
Labels: hacktoberfest-accepted

#190 Created quest add on to player state
  src/factories/player.factory.js
  src/factories/quest.factory.js
  src/interactions/map_campus_house_1/index.js
  src/interactions/map_city/enterMapStartRight.interactions.js
  src/interactions/map_start/bruno.interaction.js
  src/interactions/map_start/enterMapCityLeft.interaction.js
  src/interactions/map_start/enterMapCityRight.interactions.js
  src/interactions/map_start/restroom.interactions.js
  src/interactions/quests/constants.quests.js
  src/utils/gameState.js
  src/utils/questHandler.js
Labels: hacktoberfest-accepted

#189 feature: added dining room table interaction
  src/interactions/map_campus_house_1/dining_room_table.interaction.js
  src/interactions/map_campus_house_1/index.js
Labels: hacktoberfest-accepted

#191 Added quest bug fix
  src/interactions/map_start/enterMapCityLeft.interaction.js
  src/interactions/map_start/enterMapCityRight.interactions.js
Labels: hacktoberfest-accepted

#193 Game machine 5 interaction
  asset_credits.md
  public/assets/sprites/ballGrey.png
  public/assets/sprites/element_blue_rectangle_glossy.png
  public/assets/sprites/element_green_rectangle_glossy.png
  public/assets/sprites/element_red_rectangle_glossy.png
  public/assets/sprites/element_yellow_rectangle_glossy.png
  public/assets/sprites/paddleRed.png
  src/interactions/map_arcade/game_machine_5.interactions.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted

#195 add missing import to file
  src/interactions/map_campus_house_1/index.js
Labels: hacktoberfest-accepted

#196 Extended Campus Map
  public/exports/maps/map_extended_campus.png
  public/maps/map_city.json
  public/maps/map_extended_campus.json
  src/core/kaplay/sounds/index.js
  src/gameObjects/map_extended_campus/index.js
  src/interactions/map_city/enterMapExtendCampusTop.interactions.js
  src/interactions/map_city/enterMapExtendedCampus.interactions.js
  src/interactions/map_city/index.js
  src/interactions/map_extended_campus/campusTreeInteraction.interactions.js
  src/interactions/map_extended_campus/enterMapCityLeft.interactions.js
  src/interactions/map_extended_campus/enterMapCityTop.interactions.js
  src/interactions/map_extended_campus/fountainInteraction.interactions.js
  src/interactions/map_extended_campus/index.js
  src/interactions/map_extended_campus/signLeftInteraction.interactions.js
  src/interactions/map_extended_campus/signRightInteraction.interactions.js
  src/interactions/map_extended_campus/treeSignInteraction.interactions.js
  src/main.js
  src/scenes/extended_campus.js
Labels: hacktoberfest-accepted

#197 Added Realtor Map & Quest
  public/exports/maps/map_realtor.png
  public/maps/map_realtor.json
  src/gameObjects/map_realtor/clerk.gameObjects.js
  src/gameObjects/map_realtor/index.js
  src/interactions/map_extended_campus/enterMapRealtor.interactions.js
  src/interactions/map_extended_campus/index.js
  src/interactions/map_realtor/behindDeskClerkInteraction.interactions.js
  src/interactions/map_realtor/boxesInteraction.interactions.js
  src/interactions/map_realtor/computerOneInteraction.interactions.js
  src/interactions/map_realtor/computerTwoInteraction.interactions.js
  src/interactions/map_realtor/counterClerkInteraction.interactions.js
  src/interactions/map_realtor/enterMapExtendedCampus.interactions.js
  src/interactions/map_realtor/fridgeInteraction.interactions.js
  src/interactions/map_realtor/index.js
  src/interactions/quests/constants.quests.js
  src/main.js
  src/scenes/realtor.js
Labels: hacktoberfest-accepted

#199 add in flying bird asset to city map plus sprite sheet and credits
  asset_credits.md
  public/assets/sprites/bird_flying.png
  src/gameObjects/map_city/flyingBirds.js
  src/gameObjects/map_city/index.js
Labels: hacktoberfest-accepted

#202 Create a mini game like the offline dino game in the arcade room for game machine 7
  asset_credits.md
  public/assets/sprites/runner-quest-background.png
  public/assets/sprites/runner-quest-barrier.png
  public/assets/sprites/runner-quest-player.png
  src/interactions/map_arcade/game_machine_7.interaction.js
  src/interactions/map_arcade/index.js
Labels: hacktoberfest-accepted
